source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'pg'
gem 'unicorn'
gem 'uglifier'
gem 'jquery-rails'
gem 'jquery-fileupload-rails'
gem 'backbone-on-rails'
gem 'sass-rails'
gem 'bootstrap-sass'
gem 'carrierwave'
gem 'kaminari'
gem 'taglib-ruby'
gem 'bcrypt-ruby'
gem 'haml'
gem 'devise'
gem 'quiet_assets', :group => :development
gem 'thin'
