source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem 'pg', '~>0.14.1'
gem 'unicorn'
gem 'uglifier', '>= 1.0.3'
gem 'jquery-rails'
gem 'jquery-fileupload-rails'
gem 'backbone-on-rails'
gem 'sass-rails',   '~> 3.2.3'
gem 'bootstrap-sass'
gem 'carrierwave'
gem 'kaminari'
gem 'taglib-ruby'
gem 'bcrypt-ruby'
gem 'haml'
gem 'devise'
gem 'quiet_assets', :group => :development
gem 'thin'